[features]
seeds = false
skip-lint = false

[programs.devnet]
lineup-protocol = "F1fSaEwdEzaSMvFcoHSmiCEToY1HFBHjUGYmqJiGkn9X"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/Users/dannpl/.config/solana/id.json"

[scripts]
test = "yarn anchor-tests"
